local cm = require("criticmarkup")

local function set_buf(lines)
  vim.cmd("enew!")
  vim.api.nvim_buf_set_lines(0, 0, -1, false, lines)
end

local function get_buf()
  return vim.api.nvim_buf_get_lines(0, 0, -1, false)
end

describe("accept at cursor", function()
  it("keeps addition text", function()
    set_buf({ "one {++added++} word" })
    vim.api.nvim_win_set_cursor(0, { 1, 7 })
    cm.accept()
    assert.are.same({ "one added word" }, get_buf())
  end)

  it("removes deletion", function()
    set_buf({ "two {--deleted --}word" })
    vim.api.nvim_win_set_cursor(0, { 1, 7 })
    cm.accept()
    assert.are.same({ "two word" }, get_buf())
  end)

  it("applies substitution", function()
    set_buf({ "the {~~bird~>condor~~} flew" })
    vim.api.nvim_win_set_cursor(0, { 1, 7 })
    cm.accept()
    assert.are.same({ "the condor flew" }, get_buf())
  end)

  it("strips highlight markup, keeping text", function()
    set_buf({ "a {==marked==} word" })
    vim.api.nvim_win_set_cursor(0, { 1, 5 })
    cm.accept()
    assert.are.same({ "a marked word" }, get_buf())
  end)

  it("removes comment entirely", function()
    set_buf({ "done.{>> really? <<}" })
    vim.api.nvim_win_set_cursor(0, { 1, 8 })
    cm.accept()
    assert.are.same({ "done." }, get_buf())
  end)

  it("finds the second annotation on a line", function()
    set_buf({ "{++first++} and {++second++} end" })
    vim.api.nvim_win_set_cursor(0, { 1, 19 })
    cm.accept()
    assert.are.same({ "{++first++} and second end" }, get_buf())
  end)

  it("handles annotations spanning lines", function()
    set_buf({ "a {++x", "y++} b" })
    vim.api.nvim_win_set_cursor(0, { 1, 3 })
    cm.accept()
    assert.are.same({ "a x", "y b" }, get_buf())
  end)

  it("leaves the buffer alone when there is no annotation", function()
    set_buf({ "plain text" })
    vim.api.nvim_win_set_cursor(0, { 1, 2 })
    cm.accept()
    assert.are.same({ "plain text" }, get_buf())
  end)
end)

describe("reject at cursor", function()
  it("removes addition", function()
    set_buf({ "one {++added ++}word" })
    vim.api.nvim_win_set_cursor(0, { 1, 7 })
    cm.reject()
    assert.are.same({ "one word" }, get_buf())
  end)

  it("keeps deletion text", function()
    set_buf({ "two {--deleted--} word" })
    vim.api.nvim_win_set_cursor(0, { 1, 7 })
    cm.reject()
    assert.are.same({ "two deleted word" }, get_buf())
  end)

  it("keeps the original in substitution", function()
    set_buf({ "the {~~bird~>condor~~} flew" })
    vim.api.nvim_win_set_cursor(0, { 1, 7 })
    cm.reject()
    assert.are.same({ "the bird flew" }, get_buf())
  end)

  it("strips highlight markup, keeping text", function()
    set_buf({ "a {==marked==} word" })
    vim.api.nvim_win_set_cursor(0, { 1, 5 })
    cm.reject()
    assert.are.same({ "a marked word" }, get_buf())
  end)
end)

describe("range processing", function()
  it("resolves every annotation in the range and nothing outside it", function()
    set_buf({
      "1 {++a++} {--b--}",
      "2 {~~c~>d~~}",
      "3 {++outside++}",
    })
    cm.accept_range(1, 2)
    assert.are.same({ "1 a ", "2 d", "3 {++outside++}" }, get_buf())
  end)
end)

describe("navigation", function()
  it("jumps to next and previous annotations", function()
    set_buf({ "plain", "x {--del--}", "y {++add++}" })
    vim.api.nvim_win_set_cursor(0, { 1, 0 })
    cm.next()
    assert.are.same({ 2, 2 }, vim.api.nvim_win_get_cursor(0))
    cm.next()
    assert.are.same({ 3, 2 }, vim.api.nvim_win_get_cursor(0))
    cm.prev()
    assert.are.same({ 2, 2 }, vim.api.nvim_win_get_cursor(0))
  end)
end)

describe("creating annotations", function()
  it("wraps a charwise region", function()
    set_buf({ "delete this word" })
    cm.annotate("deletion")
    vim.api.nvim_buf_set_mark(0, "[", 1, 7, {})
    vim.api.nvim_buf_set_mark(0, "]", 1, 10, {})
    cm._opfunc("char")
    assert.are.same({ "delete {--this--} word" }, get_buf())
  end)

  it("wraps lines and positions the cursor for substitutions", function()
    set_buf({ "first", "second" })
    cm.annotate("substitution")
    vim.api.nvim_buf_set_mark(0, "[", 1, 0, {})
    vim.api.nvim_buf_set_mark(0, "]", 2, 0, {})
    cm._opfunc("line")
    assert.are.same({ "{~~", "first", "second", "~>~~}" }, get_buf())
    assert.are.same({ 4, 2 }, vim.api.nvim_win_get_cursor(0))
  end)
end)

describe("highlighting", function()
  it("places extmarks for annotations", function()
    set_buf({ "one {++added++} word and {>>a note<<}" })
    cm.refresh(0)
    local marks = vim.api.nvim_buf_get_extmarks(0, vim.api.nvim_create_namespace("criticmarkup"), 0, -1, {})
    assert.are.equal(6, #marks) -- two annotations x (open + content + close)
  end)
end)
